### ISSUE TITLE
Strong integrity passed but not Virtual one

### ISSUE THREAD

**Issue by popis1** [chiteroman/TrickyStore#7]
As i mension in title Strong integrity passed but Virtual Integrity is falls. Its possible to have pass Virtual Integrity on rooted device? I have my own unrevoked keybox.xml
![1723735569736](https://github.com/user-attachments/assets/6807dda2-789c-4dd4-b343-9e4885d9480b)
![1723735569715](https://github.com/user-attachments/assets/09fa87a6-68ce-4a43-beeb-54600006b49c)

**Comment by DESK-coder** [comment]
That's right because you don't have an emulator but a real device.

**Comment by chiteroman** [comment]
Can you read?
